# Generated by Django 2.1.2 on 2018-12-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcdsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornpro',
            name='ins_nm',
            field=models.CharField(default='', help_text='机构名称', max_length=64),
        ),
    ]
