# Generated by Django 2.1.2 on 2018-12-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcdsApp', '0003_netinfo_ins_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyinfo',
            name='acc_ecds',
            field=models.IntegerField(default=0, help_text='网络接入方式', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='netinfo',
            name='IP_R2C1',
            field=models.CharField(help_text='参与者外联通信IP地址', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='netinfo',
            name='ip',
            field=models.CharField(help_text='参与者 VPN接入设备公网地址', max_length=32, null=True),
        ),
    ]
