# Generated by Django 2.1.2 on 2018-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcdsApp', '0004_auto_20181210_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyinfo',
            name='acc_ecds',
            field=models.CharField(default=0, help_text='网络接入方式', max_length=16, null=True),
        ),
    ]
