# Generated by Django 2.1.2 on 2018-12-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcdsApp', '0005_auto_20181210_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='insinfo',
            name='pay_num',
            field=models.CharField(default='', help_text='支付系统行号', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='insinfo',
            name='sum_num',
            field=models.CharField(default='', help_text='总行行号', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='insinfo',
            name='vip_code',
            field=models.CharField(default='', help_text='会员代码', max_length=16, null=True),
        ),
    ]
