# Generated by Django 2.1.2 on 2018-12-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcdsApp', '0006_auto_20181212_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornpro',
            name='mbfe_type',
            field=models.CharField(default='', help_text='MBFE版本', max_length=64),
        ),
    ]
