# Generated by Django 2.1.2 on 2019-01-14 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EcdsApp', '0008_auto_20181217_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softinfo',
            name='MBFE',
        ),
        migrations.RemoveField(
            model_name='softinfo',
            name='apply_mid',
        ),
        migrations.RemoveField(
            model_name='softinfo',
            name='front_info',
        ),
        migrations.RemoveField(
            model_name='softinfo',
            name='message_mid',
        ),
        migrations.RemoveField(
            model_name='softinfo',
            name='pro_acc_num',
        ),
        migrations.RemoveField(
            model_name='softinfo',
            name='pro_line_num',
        ),
        migrations.RemoveField(
            model_name='softinfo',
            name='test_acc_num',
        ),
        migrations.RemoveField(
            model_name='softinfo',
            name='test_line_num',
        ),
        migrations.AddField(
            model_name='acceptcheck',
            name='Spare',
            field=models.CharField(default='', help_text='备用字段', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='acceptcheck',
            name='check_state',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '驳回')], default=0, help_text='审核状态'),
        ),
        migrations.AddField(
            model_name='softinfo',
            name='Spare',
            field=models.CharField(default='', help_text='备用字段', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='softinfo',
            name='acces_type',
            field=models.CharField(default='', help_text='接入方式', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='softinfo',
            name='test_descrip',
            field=models.TextField(default=django.utils.timezone.now, help_text='测试说明', max_length=512),
            preserve_default=False,
        ),
    ]
