# Generated by Django 2.1.2 on 2019-01-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcdsApp', '0009_auto_20190114_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_user', models.CharField(help_text='上传人', max_length=32)),
                ('up_date', models.DateTimeField(auto_now=True, help_text='上传时间', null=True)),
                ('file_nm', models.CharField(help_text='上传文件名称', max_length=64)),
                ('file_url', models.CharField(help_text='文件上传路径', max_length=32)),
                ('check_status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=0, help_text='审核状态')),
                ('end_time', models.DateTimeField(auto_now_add=True, help_text='失效时间')),
                ('priority', models.IntegerField(blank=True, default=9, help_text='优先级', null=True)),
                ('spare', models.CharField(default='', help_text='备用字段', max_length=16, null=True)),
            ],
        ),
    ]
