# Generated by Django 2.1.2 on 2019-01-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcdsApp', '0012_auto_20190122_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfile',
            options={'verbose_name': '检测技术文档', 'verbose_name_plural': '检测技术文档'},
        ),
        migrations.AlterModelTable(
            name='testfile',
            table='testfile',
        ),
    ]
